// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ9aANPZnr7gCUjKCVCUY10QEBI2YFMhg',
    appId: '1:279120469775:android:0ae17f5f233961e134287a',
    messagingSenderId: '279120469775',
    projectId: 'coleccion-app-de9bd',
    storageBucket: 'coleccion-app-de9bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4g52aAlkj_z5ZbVJ9eU-r7xe5U4rDXO8',
    appId: '1:279120469775:ios:acd5c2f75b60d59e34287a',
    messagingSenderId: '279120469775',
    projectId: 'coleccion-app-de9bd',
    storageBucket: 'coleccion-app-de9bd.firebasestorage.app',
    iosBundleId: 'com.example.coleccionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBGVmbcBhwpKtO3CBBj7OWgA5OGYxC0_c',
    appId: '1:279120469775:web:bf5b6a62820e8f8334287a',
    messagingSenderId: '279120469775',
    projectId: 'coleccion-app-de9bd',
    authDomain: 'coleccion-app-de9bd.firebaseapp.com',
    storageBucket: 'coleccion-app-de9bd.firebasestorage.app',
    measurementId: 'G-R5JM6CP6EF',
  );
}
